task:
  name: "Sweet 3"
  trigger_type: manual
  timeout_in: 1h
  container:
      image: nexgang/ubuntu:latest
      cpu: 8
      memory: 32G
      
  setup_script:
    - ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && date
    - apt update && apt upgrade -y
            
  Build_script:
      - bash clanglinaro.sh
